// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_State int32

const (
	Order_Pending   Order_State = 0
	Order_Completed Order_State = 1
	Order_Rejected  Order_State = 2
	Order_Issue     Order_State = 3
)

var Order_State_name = map[int32]string{
	0: "Pending",
	1: "Completed",
	2: "Rejected",
	3: "Issue",
}

var Order_State_value = map[string]int32{
	"Pending":   0,
	"Completed": 1,
	"Rejected":  2,
	"Issue":     3,
}

func (x Order_State) String() string {
	return proto.EnumName(Order_State_name, int32(x))
}

func (Order_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0, 0}
}

type Order struct {
	OrderId              string               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	State                Order_State          `protobuf:"varint,2,opt,name=state,proto3,enum=Order_State" json:"state,omitempty"`
	Bet                  uint64               `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`
	GameId               string               `protobuf:"bytes,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId               string               `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt          *timestamp.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetState() Order_State {
	if m != nil {
		return m.State
	}
	return Order_Pending
}

func (m *Order) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *Order) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("Order_State", Order_State_name, Order_State_value)
	proto.RegisterType((*Order)(nil), "Order")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x6f, 0x83, 0x30,
	0x14, 0xc4, 0xeb, 0x24, 0xfc, 0x7b, 0xd0, 0x0a, 0x79, 0x29, 0xcd, 0x52, 0xc4, 0xc4, 0xe4, 0x48,
	0xe9, 0x54, 0xa9, 0x1d, 0x50, 0x27, 0xa6, 0x56, 0xb4, 0x7b, 0x04, 0xf8, 0x15, 0x51, 0x85, 0x18,
	0xc1, 0xe3, 0xe3, 0x57, 0xaa, 0x6c, 0xa0, 0x6b, 0x36, 0x9f, 0xef, 0x7e, 0x67, 0x9d, 0xc1, 0x57,
	0x83, 0xc4, 0x41, 0xf4, 0x83, 0x22, 0xb5, 0x7f, 0x6c, 0x94, 0x6a, 0xce, 0x78, 0x30, 0xaa, 0x9a,
	0xbe, 0x0f, 0xd4, 0x76, 0x38, 0x52, 0xd9, 0xf5, 0x73, 0x20, 0xf9, 0xdd, 0x80, 0xf5, 0xae, 0x01,
	0xfe, 0x00, 0xae, 0x21, 0x4f, 0xad, 0x8c, 0x58, 0xcc, 0x52, 0xaf, 0x70, 0x8c, 0xce, 0x25, 0x4f,
	0xc0, 0x1a, 0xa9, 0x24, 0x8c, 0x36, 0x31, 0x4b, 0xef, 0x8e, 0x81, 0x30, 0x84, 0xf8, 0xd4, 0x77,
	0xc5, 0x6c, 0xf1, 0x10, 0xb6, 0x15, 0x52, 0xb4, 0x8d, 0x59, 0xba, 0x2b, 0xf4, 0x91, 0xdf, 0x83,
	0xd3, 0x94, 0x1d, 0xea, 0xbe, 0x9d, 0xe9, 0xb3, 0xb5, 0xcc, 0xa5, 0x36, 0xa6, 0x71, 0x7e, 0xc8,
	0x9a, 0x0d, 0x2d, 0x73, 0xc9, 0x9f, 0x01, 0xea, 0x01, 0x4b, 0x42, 0x79, 0x2a, 0x29, 0xb2, 0x63,
	0x96, 0xfa, 0xc7, 0xbd, 0x98, 0x27, 0x88, 0x75, 0x82, 0xf8, 0x5a, 0x27, 0x14, 0xde, 0x92, 0xce,
	0x48, 0xa3, 0x53, 0x2f, 0x57, 0xd4, 0xb9, 0x8e, 0x2e, 0xe9, 0x8c, 0xf8, 0x2b, 0x04, 0xb5, 0xea,
	0xfa, 0x33, 0x2e, 0xb0, 0x7b, 0x15, 0xf6, 0xff, 0xf3, 0x19, 0x25, 0x2f, 0x60, 0x99, 0x8f, 0xe0,
	0x3e, 0x38, 0x1f, 0x78, 0x91, 0xed, 0xa5, 0x09, 0x6f, 0xf8, 0x2d, 0x78, 0x6f, 0x6b, 0x28, 0x64,
	0x3c, 0x00, 0xb7, 0xc0, 0x1f, 0xac, 0xb5, 0xda, 0x70, 0x0f, 0xac, 0x7c, 0x1c, 0x27, 0x0c, 0xb7,
	0x95, 0x6d, 0xea, 0x9f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xb8, 0x4f, 0xce, 0xb6, 0x01,
	0x00, 0x00,
}
