CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$

BEGIN
  NEW.updated_at = NOW();
  
  RETURN NEW;
END;

$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS games (
	id BIGSERIAL NOT NULL PRIMARY KEY,

	name VARCHAR(50) NOT NULL,

	href TEXT NOT NULL,

	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service;

GRANT ALL on games_id_seq to service;
