#!/usr/bin/env bash

container_name=pg
password=123456

docker run \
	--rm \
	--name $container_name \
	-e POSTGRES_PASSWORD=$password \
	-d \
	-p 5432:5432 \
	-v $HOME/docker/volumes/postgres:/var/lib/postgresql/data \
	postgres
