### Token
POST http://34.94.53.107:9000/v1/token
Content-Type: application/json
Session: abcd1234

{
    "game": "catpunch",
    "username": "kayac"
}

### Game
POST http://34.94.53.107:9000/v1/games
Content-Type: application/json

{
    "name": "catpunch",
    "href": "https://catpunch",
    "category": "slot"
}

### Game
GET http://localhost:8000/v1/games
