@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}

### Create Admin
# @username = "kayac"
# @password = "Test123456."
# @secret = "my_secret_key"
# @email = "egg734631@gmail.com"

POST http://{{host}}/v1/admins
Content-Type: application/json

{
    "secret": {{secret}},
    "email": {{email}},
    "username": {{username}},
    "password": {{password}}
}

### Create Admin Token
@password = "Test123456."
@secret = "my_secret_key"
@email = "egg734631@gmail.com"
# @name adminToken
POST http://{{host}}/v1/admins/tokens
Content-Type: application/json

{
    "secret": {{secret}},
    "email": {{email}},
    "password": {{password}}
}

###
@authToken = {{adminToken.response.body.$.data.access_token}}

### Find Game
@gameurl = d52d3013075fe1078c47236cdc338422

GET http://{{host}}/v1/games/{{gameurl}}
Authorization: Bearer {{authToken}}

### Get Game Links
GET http://{{host}}/v1/games

### Create Game
@gamename = "cyberpunk"
@href = "https://cyberpunk-dev.sunnyland.fun"
@category = "slot"
POST http://{{host}}/v1/games
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": {{gamename}},
    "href": {{href}},
    "category": {{category}}
}

### Update Game
@href = "https://cyberpunk-dev.sunnyland.fun"
@category = "slot"
PUT http://{{host}}/v1/games/{{gameurl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": {{gamename}},
    "href": {{href}},
    "category": {{category}}
}

### Token
# @session = dfd99af9-f92f-4161-8e62-9598fb38931b
# @game = "cyberpunk"
# @username = "mouse1"
# @name gameToken
POST http://{{host}}/v1/tokens
Content-Type: application/json
Session: {{session}}

{
    "game": {{game}},
    "username": {{username}}
}

### 
@access_token = {{gameToken.response.body.$.data.token.access_token}}

### Game Init
# @name gameInit
POST http://localhost:8000/game/init
Authorization: Bearer {{access_token}}

###
@gametypeid = {{gameInit.response.body.$.data.player.gametypeid}}

@betrate = {{gameInit.response.body.$.data.betrate.betratelinkindex[0]}}

POST http://localhost:8000/game/result
Authorization: Bearer {{access_token}}

{
    "gametypeid": "{{gametypeid}}",
    "bet": {{betrate}}
}
