@hostname = 127.0.0.1
@port = 8000
@host = {{hostname}}:{{port}}

### Create Admin
@username = "kayac"
@password = "Test123456."
@organization = "sunny"
@secret = "my_secret_key"
@email = "egg734631@gmail.com"

POST http://{{host}}/v1/admins
Content-Type: application/json

{
    "secret": {{secret}},
    "email": {{email}},
    "username": {{username}},
    "password": {{password}},
    "organization": {{organization}}
}

### Create Admin Token
@password = "Test123456."
@secret = "my_secret_key"
@email = "egg734631@gmail.com"
# @name adminToken
POST http://{{host}}/v1/admins/tokens
Content-Type: application/json

{
    "secret": {{secret}},
    "email": {{email}},
    "password": {{password}}
}

###
@authToken = {{adminToken.response.body.$.data.access_token}}

### Find Game
@gameurl = catpunch

GET http://{{host}}/v1/games/{{gameurl}}
Authorization: Bearer {{authToken}}

### Get Game Links
GET http://{{host}}/v1/games

### Create Game
@gamename = "catpunch"
@href = "https://catpunch"
@category = "slot"
POST http://{{host}}/v1/games
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": {{gamename}},
    "href": {{href}},
    "category": {{category}}
}

### Update Game
# @gamename = "catpunch"
# @href = "https://catpunch"
@category = "slot"
PUT http://{{host}}/v1/games/{{gameurl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": {{gamename}},
    "href": {{href}},
    "category": {{category}}
}

### Token
@session = dfd99af9-f92f-4161-8e62-9598fb38931b
@game = "catpunch"
@username = "mouse1"
POST http://{{host}}/v1/tokens
Content-Type: application/json
Session: {{session}}

{
    "game": {{game}},
    "username": {{username}}
}