
# === First ===

### Normal Case => pass
POST https://localhost:8081/users HTTP/2.0
content-type: application/json

{
    "username": "kayac",
    "password": "123456"
}

### 
POST https://localhost:8081/token HTTP/2.0
content-type: application/json

{
    "username": "kayac",
    "password": "123456"
}
